# Enable official GitHub Sponsors keys only if the project accepts funding.
#
github: [aibersemi]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
custom: ["https://saweria.co/aibersemi"]
