# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_mapping",
            },
        ),
        migrations.CreateModel(
            name="ReconciliationIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=200)),
                ("issue_type", models.CharField(max_length=80)),
                ("detail", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Terbuka"), ("resolved", "Selesai")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_reconciliation_issue",
            },
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="reopen_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="reopened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reopened_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_automatic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversed_by_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_of",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Terbuka"),
                    ("closing", "Proses Tutup Buku"),
                    ("closed", "Ditutup"),
                    ("reopened", "Dibuka Kembali"),
                ],
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit", 0), ("debit__gt", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="journal_line_one_side",
            ),
        ),
        migrations.AddField(
            model_name="accountingmapping",
            name="credit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="credit_mappings",
                to="masterdata.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="accountingmapping",
            name="debit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="debit_mappings",
                to="masterdata.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="accountingmapping",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="reconciliationissue",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingmapping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "event_type"), name="uniq_accounting_mapping"
            ),
        ),
    ]
