# Generated by Django 6.0.6 on 2026-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_accountingmapping_reconciliationissue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="reference",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Referensi Sumber"
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Keterangan Baris"
            ),
        ),
    ]
