# Generated by Django 6.0.6 on 2026-06-21 05:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versi"),
                ),
                ("effective_date", models.DateField(verbose_name="Tanggal Efektif")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_bom",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nama Pelanggan"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Alamat"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_customer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Kode Material")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nama Material"),
                ),
                (
                    "conversion_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Rasio Konversi (Beli -> Pakai)",
                    ),
                ),
                (
                    "moq",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="MOQ Beli",
                    ),
                ),
                (
                    "purchase_multiple",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="Kelipatan Beli",
                    ),
                ),
                (
                    "shrinkage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Persentase Waste/Shrinkage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_material",
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Kuantitas (Satuan Pakai)",
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="masterdata.bom",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.material",
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_bom_item",
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nama Operator"),
                ),
                (
                    "operator_type",
                    models.CharField(
                        choices=[
                            ("penjahit", "Penjahit"),
                            ("maklon", "Maklon (Luar)"),
                            ("potong", "Tukang Potong"),
                            ("sablon", "Tukang Sablon"),
                            ("gudang", "Petugas Gudang"),
                            ("pembelian", "Petugas Pembelian"),
                            ("qc", "Petugas QC"),
                            ("packing", "Petugas Packing"),
                            ("mandor", "Mandor"),
                            ("dapur", "Petugas Dapur"),
                        ],
                        max_length=30,
                        verbose_name="Tipe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("external", "Eksternal (Luar)"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Lokasi Kerja",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Telepon"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_operator",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Kode Model")),
                ("name", models.CharField(max_length=255, verbose_name="Nama Model")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Deskripsi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_product_model",
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="PieceRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "stage_name",
                    models.CharField(
                        max_length=100, verbose_name="Nama Tahap (Routing)"
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tarif"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Tanggal Efektif")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_rates",
                        to="masterdata.operator",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masterdata.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_piece_rate",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("sku", models.CharField(max_length=100, verbose_name="SKU")),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Warna"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Ukuran"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="masterdata.productmodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_product_variant",
                "unique_together": {("tenant", "sku")},
            },
        ),
        migrations.AddField(
            model_name="bom",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boms",
                to="masterdata.productvariant",
            ),
        ),
        migrations.CreateModel(
            name="Routing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versi"),
                ),
                ("effective_date", models.DateField(verbose_name="Tanggal Efektif")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routings",
                        to="masterdata.productmodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_routing",
                "unique_together": {("tenant", "product_model", "version")},
            },
        ),
        migrations.CreateModel(
            name="RoutingStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="Urutan")),
                (
                    "stage_name",
                    models.CharField(max_length=100, verbose_name="Nama Tahap"),
                ),
                (
                    "routing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="masterdata.routing",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_routing_stage",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nama Pemasok")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Kontak Person",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Alamat"),
                ),
                (
                    "payment_info",
                    models.TextField(
                        blank=True, default="", verbose_name="Info Pembayaran"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_supplier",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="material",
            name="default_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="masterdata.supplier",
            ),
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Kode Satuan")),
                ("name", models.CharField(max_length=50, verbose_name="Nama Satuan")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_uom",
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.AddField(
            model_name="material",
            name="purchase_uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="masterdata.uom",
                verbose_name="Satuan Beli",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="usage_uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="masterdata.uom",
                verbose_name="Satuan Pakai",
            ),
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Kode Akun")),
                ("name", models.CharField(max_length=200, verbose_name="Nama Akun")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                        verbose_name="Tipe Akun",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "masterdata_coa",
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bom",
            unique_together={("tenant", "product_variant", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together={("tenant", "code")},
        ),
    ]
