# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("name", models.CharField(max_length=150)),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "account_holder",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("is_cash", models.BooleanField(default=False)),
                ("is_petty_cash", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "masterdata_bank_account",
            },
        ),
        migrations.CreateModel(
            name="CostCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=150)),
                (
                    "allocation_basis",
                    models.CharField(
                        choices=[
                            ("quantity", "Jumlah Produk"),
                            ("direct_cost", "Biaya Langsung"),
                            ("manual", "Manual"),
                        ],
                        default="quantity",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "masterdata_cost_category",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("label", models.CharField(default="Utama", max_length=80)),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField()),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "masterdata_customer_address",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="package_quantity",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                max_digits=15,
                verbose_name="Isi per Kemasan",
            ),
        ),
        migrations.AddField(
            model_name="operator",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="masterdata.operator",
            ),
        ),
        migrations.AddField(
            model_name="operator",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operator_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="piecerate",
            name="change_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="piecerate",
            name="effective_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="piecerate",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="piecerate",
            name="operator_status",
            field=models.CharField(
                blank=True,
                choices=[("internal", "Internal"), ("external", "Eksternal (Luar)")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="default_margin_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
        ),
        migrations.AddField(
            model_name="routingstage",
            name="requires_qc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="routingstage",
            name="transition_rule",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Aturan Perpindahan"
            ),
        ),
        migrations.AddField(
            model_name="uom",
            name="dimension",
            field=models.CharField(
                choices=[
                    ("count", "Jumlah"),
                    ("length", "Panjang"),
                    ("mass", "Berat"),
                    ("volume", "Volume"),
                ],
                default="count",
                max_length=20,
                verbose_name="Dimensi",
            ),
        ),
        migrations.AddConstraint(
            model_name="operator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("tenant", "user"),
                name="uniq_operator_user_per_tenant",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="chart_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="costcategory",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="costcategory",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="masterdata.customer",
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_account_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="costcategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_cost_category"
            ),
        ),
    ]
