# Generated by Django 6.0.6 on 2026-06-21 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("inventory", "0003_initial"),
        ("masterdata", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nama Aset")),
                ("category", models.CharField(max_length=100, verbose_name="Kategori")),
                (
                    "acquisition_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Nilai Perolehan"
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(verbose_name="Tanggal Perolehan"),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(verbose_name="Umur Ekonomis (Bulan)"),
                ),
                (
                    "depreciation_start_date",
                    models.DateField(verbose_name="Tanggal Mulai Penyusutan"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("inactive", "Tidak Digunakan"),
                            ("broken", "Rusak"),
                            ("sold", "Dijual/Dilepas"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Lokasi"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_asset",
            },
        ),
        migrations.CreateModel(
            name="CustomerInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="Nomor Invoice"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Invoice")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Jatuh Tempo"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total Tagihan"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sudah Dibayar",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("unpaid", "Belum Dibayar/DP"),
                            ("partial", "Dibayar Sebagian"),
                            ("paid", "Lunas"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.customer",
                    ),
                ),
                (
                    "sales_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoices",
                        to="sales.salespo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_customer_invoice",
                "unique_together": {("tenant", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Pembayaran")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Nominal Pembayaran",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Metode Pembayaran"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referensi"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="finance.customerinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_customer_payment",
            },
        ),
        migrations.CreateModel(
            name="DepreciationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Penyusutan")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Nominal Penyusutan",
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(default=False, verbose_name="Sudah Diposting"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciations",
                        to="finance.asset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_asset_depreciation",
            },
        ),
        migrations.CreateModel(
            name="PettyCashTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Transaksi")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("in", "Uang Masuk (Pengisian)"),
                            ("out", "Uang Keluar (Pengeluaran)"),
                        ],
                        max_length=10,
                        verbose_name="Jenis Transaksi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Nominal"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kategori Pengeluaran",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Keterangan"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("verified", "Diverifikasi"),
                            ("posted", "Dibukukan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pic",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Penanggung Jawab",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_petty_cash_transaction",
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=100, verbose_name="Nomor Invoice Pemasok"
                    ),
                ),
                ("date", models.DateField(verbose_name="Tanggal Invoice")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Jatuh Tempo"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total Tagihan"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sudah Dibayar",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Belum Dibayar"),
                            ("partial", "Dibayar Sebagian"),
                            ("paid", "Lunas"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoices",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_supplier_invoice",
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Pembayaran")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Nominal Pembayaran",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Metode Pembayaran"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Referensi (No. Cek/Transfer)",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="finance.supplierinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_supplier_payment",
            },
        ),
    ]
