# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_accountingmapping_reconciliationissue_and_more"),
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("finance", "0001_initial"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        (
            "production",
            "0003_hppsnapshot_materialconsumption_materialrequirement_and_more",
        ),
        ("sales", "0002_delivery_deliveryline_salesreturn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="depreciation_method",
            field=models.CharField(
                choices=[("straight_line", "Garis Lurus")],
                default="straight_line",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="disposal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="disposal_proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="disposal_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="asset",
            name="disposal_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="adjustment_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="sales_po",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sales.salespo",
            ),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="petty_cash_transactions",
                to="masterdata.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="claimant_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_petty_cash",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="funding_mode",
            field=models.CharField(
                choices=[
                    ("advance", "Uang Muka"),
                    ("reimbursement", "Reimbursement"),
                    ("mixed", "Kombinasi"),
                    ("company_fund", "Dana Konveksi"),
                ],
                default="company_fund",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="meal_people_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="purchased_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pettycashtransaction",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_petty_cash",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="recipient",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktif"),
                    ("inactive", "Tidak Digunakan"),
                    ("broken", "Rusak"),
                    ("sold", "Dijual/Dilepas"),
                    ("retired", "Dihentikan"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="customerpayment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments",
                to="finance.customerinvoice",
            ),
        ),
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("allocation_basis", models.CharField(max_length=50)),
                ("allocations", models.JSONField(default=list)),
                ("reason", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.costcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.accountingperiod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_cost_allocation",
            },
        ),
        migrations.CreateModel(
            name="CustomerAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.bankaccount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.customer",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.filemetadata",
                    ),
                ),
                (
                    "sales_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="sales.salespo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_customer_advance",
            },
        ),
        migrations.CreateModel(
            name="AdvanceAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="finance.customerinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.customeradvance",
                    ),
                ),
            ],
            options={
                "db_table": "finance_advance_allocation",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "related_party",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.bankaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.costcategory",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productionorder",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.filemetadata",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_expense",
            },
        ),
        migrations.CreateModel(
            name="InvoiceDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="sales.delivery"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.customerinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_invoice_delivery",
            },
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="deliveries",
            field=models.ManyToManyField(
                related_name="customer_invoices",
                through="finance.InvoiceDelivery",
                to="sales.delivery",
            ),
        ),
        migrations.CreateModel(
            name="CustomerPaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="finance.customerinvoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.customerpayment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_customer_payment_allocation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "invoice"),
                        name="uniq_payment_invoice_allocation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("request_number", models.CharField(max_length=50)),
                ("request_type", models.CharField(max_length=50)),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("recipient", models.CharField(max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Diajukan"),
                            ("waiting_finance", "Menunggu Finance"),
                            ("deferred", "Ditunda"),
                            ("paid", "Dibayar"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("defer_reason", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.bankaccount",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.filemetadata",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "finance_payment_request",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "request_number"), name="uniq_payment_request"
                    )
                ],
            },
        ),
    ]
