# Generated by Django 6.0.6 on 2026-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_asset_depreciation_method_asset_disposal_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Lokasi"
            ),
        ),
        migrations.AlterField(
            model_name="customerpayment",
            name="reference",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Referensi"
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Kategori Pengeluaran",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Keterangan"),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="pic",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Penanggung Jawab"
            ),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Referensi (No. Cek/Transfer)",
            ),
        ),
    ]
