# Generated by Django 6.0.6 on 2026-06-21 05:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Penerimaan (Masuk)"),
                            ("issue", "Pengeluaran (Keluar)"),
                            ("return", "Pengembalian (Masuk)"),
                            ("adj_in", "Penyesuaian (Masuk)"),
                            ("adj_out", "Penyesuaian (Keluar)"),
                            ("waste", "Waste/Rusak (Keluar)"),
                        ],
                        max_length=20,
                        verbose_name="Tipe Transaksi",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Kuantitas (Satuan Pakai)",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Harga Satuan (Beli)",
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(max_length=100, verbose_name="Referensi Dokumen"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Catatan"),
                ),
            ],
            options={
                "db_table": "inventory_material_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "receipt_number",
                    models.CharField(max_length=50, verbose_name="Nomor Penerimaan"),
                ),
                ("receipt_date", models.DateField(verbose_name="Tanggal Terima")),
                (
                    "supplier_do_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nomor Surat Jalan Supplier",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material_receipt",
            },
        ),
        migrations.CreateModel(
            name="ProductLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("prod_in", "Hasil Produksi (Masuk)"),
                            ("sales_out", "Pengiriman Penjualan (Keluar)"),
                            ("return_in", "Retur Penjualan (Masuk)"),
                            ("adj_in", "Penyesuaian (Masuk)"),
                            ("adj_out", "Penyesuaian (Keluar)"),
                        ],
                        max_length=20,
                        verbose_name="Tipe Transaksi",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Kuantitas")),
                (
                    "batch_lot_number",
                    models.CharField(max_length=50, verbose_name="Batch/Lot"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="HPP Aktual / COGS",
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(max_length=100, verbose_name="Referensi Dokumen"),
                ),
            ],
            options={
                "db_table": "inventory_product_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("po_number", models.CharField(max_length=50, verbose_name="Nomor PO")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Dikonfirmasi"),
                            ("partial_receipt", "Diterima Sebagian"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Nilai",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_purchase_order",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Kuantitas (Beli)"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Harga Beli"
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="Diterima",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_po_line",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("pr_number", models.CharField(max_length=50, verbose_name="Nomor PR")),
                (
                    "requested_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Kuantitas (Beli)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Diajukan"),
                            ("ordered", "Telah Dipesan"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_purchase_request",
            },
        ),
    ]
