# Generated by Django 6.0.6 on 2026-06-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("inventory", "0001_initial"),
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialledger",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.material"
            ),
        ),
        migrations.AddField(
            model_name="materialledger",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="materialreceipt",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="productledger",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productledger",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.supplier"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="materialreceipt",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="receipts",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.material"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.material"
            ),
        ),
    ]
