# Generated by Django 6.0.6 on 2026-06-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("inventory", "0002_initial"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="purchase_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.purchaserequest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorder",
            unique_together={("tenant", "po_number")},
        ),
        migrations.AlterUniqueTogether(
            name="materialreceipt",
            unique_together={("tenant", "receipt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="purchaserequest",
            unique_together={("tenant", "pr_number")},
        ),
    ]
