# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("inventory", "0003_initial"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        (
            "production",
            "0003_hppsnapshot_materialconsumption_materialrequirement_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialledger",
            name="conversion_ratio_snapshot",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="materialledger",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="material_ledger_entries",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="materialledger",
            name="proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="materialledger",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="materialledger",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialreceipt",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="materialreceipt",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productledger",
            name="from_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Siap Dijual"),
                    ("allocated", "Dialokasikan"),
                    ("in_transit", "Dalam Pengiriman"),
                    ("defect", "Cacat"),
                    ("rework", "Dalam Perbaikan"),
                    ("returned", "Retur"),
                    ("scrapped", "Rusak/Dibuang"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productledger",
            name="to_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Siap Dijual"),
                    ("allocated", "Dialokasikan"),
                    ("in_transit", "Dalam Pengiriman"),
                    ("defect", "Cacat"),
                    ("rework", "Dalam Perbaikan"),
                    ("returned", "Retur"),
                    ("scrapped", "Rusak/Dibuang"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("open", "Terbuka"),
                    ("variance", "Ada Selisih"),
                    ("reconciled", "Terekonsiliasi"),
                ],
                default="open",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="conversion_ratio_snapshot",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="invoiced_qty",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="MaterialReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("received_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("accepted_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "rejected_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                ("variance_reason", models.TextField(blank=True, default="")),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("matched", "Sesuai"),
                            ("variance", "Selisih"),
                            ("resolved", "Selesai"),
                        ],
                        default="matched",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="inventory.purchaseorderline",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.materialreceipt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material_receipt_line",
            },
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("lot_number", models.CharField(max_length=50)),
                ("received_quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                ("is_opening_balance", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Tersedia"), ("exhausted", "Habis")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="batches",
                        to="masterdata.productvariant",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_batches",
                        to="production.productionorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "inventory_product_batch",
            },
        ),
        migrations.AddField(
            model_name="productledger",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.productbatch",
            ),
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("adjustment_number", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Approval"),
                            ("approved", "Disetujui"),
                            ("posted", "Dibukukan"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.material",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.productvariant",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.filemetadata",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_adjustment",
            },
        ),
        migrations.CreateModel(
            name="StockOpname",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("opname_number", models.CharField(max_length=50)),
                ("counted_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("counted", "Selesai Hitung"),
                            ("approved", "Disetujui"),
                            ("posted", "Dibukukan"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_stock_opnames",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_opname",
            },
        ),
        migrations.CreateModel(
            name="StockOpnameLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "system_quantity",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "physical_quantity",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "difference_quantity",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("reason", models.TextField()),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.material",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.productvariant",
                    ),
                ),
                (
                    "stock_opname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockopname",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_opname_line",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("name", models.CharField(default="Gudang Utama", max_length=150)),
                ("code", models.CharField(default="WH", max_length=30)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "inventory_warehouse",
            },
        ),
        migrations.AddConstraint(
            model_name="productbatch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "lot_number"), name="uniq_product_lot"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "adjustment_number"), name="uniq_adjustment_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockopname",
            constraint=models.UniqueConstraint(
                fields=("tenant", "opname_number"), name="uniq_opname_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="one_warehouse_per_tenant"
            ),
        ),
    ]
