# Generated by Django 6.0.6 on 2026-06-21 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_notification_metadata"),
        ("inventory", "0004_materialledger_conversion_ratio_snapshot_and_more"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        (
            "production",
            "0003_hppsnapshot_materialconsumption_materialrequirement_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialledger",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="productledger",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="materialledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uniq_material_movement_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="productledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uniq_product_movement_idempotency",
            ),
        ),
    ]
