# Generated by Django 6.0.6 on 2026-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_materialledger_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productledger",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                verbose_name="HPP Aktual / COGS",
            ),
        ),
    ]
