# Generated by Django 6.0.6 on 2026-06-21 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("po_number", models.CharField(max_length=50, verbose_name="Nomor PO")),
                ("order_date", models.DateField(verbose_name="Tanggal Pesan")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tenggat Waktu"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Dikonfirmasi"),
                            ("planned", "Direncanakan"),
                            ("in_production", "Dalam Produksi"),
                            ("partial", "Terpenuhi Sebagian"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Terkunci"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versi/Revisi"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Catatan"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sales_pos",
                        to="masterdata.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "sales_po",
                "unique_together": {("tenant", "po_number")},
            },
        ),
        migrations.CreateModel(
            name="SalesPOLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Kuantitas")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Harga Jual"
                    ),
                ),
                (
                    "fulfilled_qty",
                    models.PositiveIntegerField(default=0, verbose_name="Terkirim"),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.productvariant",
                    ),
                ),
                (
                    "sales_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salespo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "sales_po_line",
            },
        ),
        migrations.CreateModel(
            name="StockAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "allocated_qty",
                    models.PositiveIntegerField(verbose_name="Kuantitas Dialokasikan"),
                ),
                (
                    "sales_po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="sales.salespoline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "sales_stock_allocation",
            },
        ),
    ]
