# Generated by Django 6.0.6 on 2026-06-21 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "delivery_number",
                    models.CharField(max_length=50, verbose_name="Nomor Surat Jalan"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Pengiriman")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("shipped", "Dikirim"),
                            ("delivered", "Diterima"),
                            ("returned", "Dikembalikan Sebagian/Penuh"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Ongkos Kirim",
                    ),
                ),
                (
                    "shipping_payer",
                    models.CharField(
                        choices=[
                            ("customer", "Pelanggan"),
                            ("company", "Konveksi"),
                            ("free", "Gratis"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="Penanggung Ongkos",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nama Penerima",
                    ),
                ),
                (
                    "received_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Diterima"
                    ),
                ),
                (
                    "sales_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="deliveries",
                        to="sales.salespo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "sales_delivery",
                "unique_together": {("tenant", "delivery_number")},
            },
        ),
        migrations.CreateModel(
            name="DeliveryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Kuantitas Dikirim"),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.delivery",
                    ),
                ),
                (
                    "sales_po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="sales.salespoline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "sales_delivery_line",
            },
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Retur")),
                ("reason", models.TextField(verbose_name="Alasan Retur")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Proses"),
                            ("rework", "Rework"),
                            ("refund", "Refund/Kerugian"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="returns",
                        to="sales.delivery",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "sales_return",
            },
        ),
    ]
