# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("finance", "0002_asset_depreciation_method_asset_disposal_date_and_more"),
        ("inventory", "0004_materialledger_conversion_ratio_snapshot_and_more"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        ("sales", "0002_delivery_deliveryline_salesreturn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPORevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("reason", models.TextField()),
            ],
            options={
                "db_table": "sales_po_revision",
            },
        ),
        migrations.CreateModel(
            name="SalesReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("inspection", "Pemeriksaan"),
                            ("rework", "Rework"),
                            ("restock", "Kembali Siap Jual"),
                            ("replace", "Kirim Ulang"),
                            ("loss", "Kerugian"),
                        ],
                        default="inspection",
                        max_length=20,
                    ),
                ),
                (
                    "loss_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "sales_return_line",
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="delivery",
            name="receipt_proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="deliveryline",
            name="product_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.productbatch",
            ),
        ),
        migrations.AddField(
            model_name="salespo",
            name="fulfillment_strategy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stock", "Stok"),
                    ("production", "Produksi"),
                    ("combined", "Gabungan"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salespo",
            name="lock_reason",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salespo",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salespo",
            name="short_close_evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="salespo",
            name="short_close_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salespo",
            name="short_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salespoline",
            name="disposition_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salespoline",
            name="produced_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="condition",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.customer",
            ),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="financial_adjustment_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="returns",
                to="finance.customerinvoice",
            ),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="replacement_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="source_returns",
                to="sales.delivery",
            ),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="return_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="product_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_allocations",
                to="inventory.productbatch",
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="released_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="stockallocation",
            constraint=models.UniqueConstraint(
                fields=("sales_po_line", "product_batch"),
                name="uniq_line_batch_allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_qty__gt", 0)),
                name="positive_stock_allocation",
            ),
        ),
        migrations.AddField(
            model_name="salesporevision",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="salesporevision",
            name="sales_po",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="sales.salespo",
            ),
        ),
        migrations.AddField(
            model_name="salesporevision",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="delivery_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="sales.deliveryline"
            ),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="sales_return",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="sales.salesreturn",
            ),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesporevision",
            constraint=models.UniqueConstraint(
                fields=("sales_po", "version"), name="uniq_sales_po_revision"
            ),
        ),
    ]
