# Generated by Django 6.0.6 on 2026-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_salesporevision_salesreturnline_delivery_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="receiver_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nama Penerima"
            ),
        ),
    ]
