# Generated by Django 6.0.6 on 2026-06-21 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("masterdata", "0001_initial"),
        ("production", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Kasbon")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Nominal"
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Sisa Belum Lunas"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Sudah Lunas"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Alasan / Catatan"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_advances",
                        to="masterdata.operator",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "labor_cash_advance",
            },
        ),
        migrations.CreateModel(
            name="PieceRatePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Pembayaran")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total Bruto"
                    ),
                ),
                (
                    "cash_advance_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Potongan Kasbon",
                    ),
                ),
                (
                    "net_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total Dibayar"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Referensi Pembayaran",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="masterdata.operator",
                    ),
                ),
                (
                    "settled_advances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="settled_by_payments",
                        to="labor.cashadvance",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "work_logs",
                    models.ManyToManyField(
                        related_name="settled_payments", to="production.operatorworklog"
                    ),
                ),
            ],
            options={
                "db_table": "labor_piece_rate_payment",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("date", models.DateField(verbose_name="Tanggal Absensi")),
                ("is_present", models.BooleanField(default=True, verbose_name="Hadir")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Catatan"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="masterdata.operator",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "labor_attendance",
                "unique_together": {("tenant", "operator", "date")},
            },
        ),
    ]
