# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("labor", "0001_initial"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        (
            "production",
            "0003_hppsnapshot_materialconsumption_materialrequirement_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="meal_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cashadvance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pieceratepayment",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pieceratepayment",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="pieceratepayment",
            name="proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="pieceratepayment",
            name="rate_adjustment_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="CashAdvanceSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "cash_advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="labor.cashadvance",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_settlements",
                        to="labor.pieceratepayment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "labor_cash_advance_settlement",
            },
        ),
        migrations.CreateModel(
            name="PieceRatePaymentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "reference_rate",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("paid_rate", models.DecimalField(decimal_places=2, max_digits=18)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("adjustment_reason", models.TextField(blank=True, default="")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="labor.pieceratepayment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "work_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_item",
                        to="production.operatorworklog",
                    ),
                ),
            ],
            options={
                "db_table": "labor_piece_rate_payment_item",
            },
        ),
    ]
