# Generated by Django 6.0.6 on 2026-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0002_attendance_meal_eligible_cashadvance_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Catatan"),
        ),
        migrations.AlterField(
            model_name="cashadvance",
            name="notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Alasan / Catatan"
            ),
        ),
        migrations.AlterField(
            model_name="pieceratepayment",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Referensi Pembayaran",
            ),
        ),
    ]
