# Generated by Django 6.0.6 on 2026-06-21 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionStageProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "qty_in",
                    models.PositiveIntegerField(default=0, verbose_name="Qty Masuk"),
                ),
                (
                    "qty_good",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Qty Baik/Lolos"
                    ),
                ),
                (
                    "qty_defect",
                    models.PositiveIntegerField(default=0, verbose_name="Qty Cacat"),
                ),
                (
                    "qty_rework",
                    models.PositiveIntegerField(default=0, verbose_name="Qty Rework"),
                ),
                (
                    "qty_scrap",
                    models.PositiveIntegerField(default=0, verbose_name="Qty Scrap"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Diverifikasi"),
                ),
            ],
            options={
                "db_table": "production_stage_progress",
            },
        ),
        migrations.CreateModel(
            name="JobPacket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "packet_number",
                    models.CharField(max_length=50, verbose_name="Nomor Paket"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Kuantitas Paket"),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.routingstage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "production_job_packet",
            },
        ),
        migrations.CreateModel(
            name="OperatorWorkLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "qty_claimed",
                    models.PositiveIntegerField(verbose_name="Qty Diklaim"),
                ),
                (
                    "piece_rate_applied",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tarif Diterapkan"
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total Bruto"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Sudah Dibayar"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.operator",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "production_operator_work_log",
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, verbose_name="Nomor SPK"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("for_po", "Untuk PO"), ("for_stock", "Untuk Stok")],
                        max_length=20,
                        verbose_name="Tipe Order",
                    ),
                ),
                (
                    "target_quantity",
                    models.PositiveIntegerField(verbose_name="Target Kuantitas"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Direncanakan"),
                            ("released", "Dirilis"),
                            ("in_progress", "Dalam Proses"),
                            ("qc_packing", "QC/Packing"),
                            ("completed", "Selesai"),
                            ("closed", "Ditutup"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Target Selesai"
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="masterdata.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "production_order",
            },
        ),
    ]
