# Generated by Django 6.0.6 on 2026-06-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
        ("masterdata", "0001_initial"),
        ("production", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="sales_po_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="sales.salespoline",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_packets",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="job_packet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="production.jobpacket",
            ),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.operator"
            ),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.routingstage",
            ),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="operatorworklog",
            name="progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="production.productionstageprogress",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productionorder",
            unique_together={("tenant", "order_number")},
        ),
        migrations.AlterUniqueTogether(
            name="jobpacket",
            unique_together={("tenant", "packet_number")},
        ),
    ]
