# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_filemetadata_resource_id_filemetadata_resource_type_and_more"),
        ("masterdata", "0002_bankaccount_costcategory_customeraddress_and_more"),
        ("production", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HPPSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimasi"),
                            ("actual", "Aktual Produksi"),
                            ("inventory", "Persediaan/COGS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=18)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                ("components", models.JSONField(default=dict)),
                ("source_versions", models.JSONField(default=dict)),
                (
                    "margin_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                (
                    "recommended_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "production_hpp_snapshot",
            },
        ),
        migrations.CreateModel(
            name="MaterialConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("issue", "Keluar"), ("return", "Kembali")],
                        default="issue",
                        max_length=20,
                    ),
                ),
                ("inventory_reference", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "production_material_consumption",
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "required_usage_qty",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "available_usage_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "reserved_usage_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "ordered_purchase_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "shortage_usage_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "recommended_purchase_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "packaging_excess_usage_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("calculation_version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "production_material_requirement",
            },
        ),
        migrations.CreateModel(
            name="MaterialReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "consumed_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "released_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "production_material_reservation",
            },
        ),
        migrations.CreateModel(
            name="ProductionCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("component", models.CharField(max_length=80)),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "allocation_basis",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "db_table": "production_cost",
            },
        ),
        migrations.CreateModel(
            name="ReworkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("result_good", models.PositiveIntegerField(default=0)),
                ("result_scrap", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Terbuka"),
                            ("in_progress", "Dikerjakan"),
                            ("passed", "Lolos"),
                            ("failed", "Gagal"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "production_rework_order",
            },
        ),
        migrations.CreateModel(
            name="ScrapRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("reason", models.TextField()),
            ],
            options={
                "db_table": "production_scrap_record",
            },
        ),
        migrations.CreateModel(
            name="WIPBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "production_wip_balance",
            },
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="assigned_operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_packets",
                to="masterdata.operator",
            ),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="external_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="external_job_packets",
                to="masterdata.supplier",
            ),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Ditugaskan"),
                    ("accepted", "Diterima"),
                    ("submitted", "Dikirim Operator"),
                    ("verified", "Diverifikasi"),
                    ("billable", "Layak Ditagihkan"),
                    ("paid", "Dibayar"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpacket",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operatorworklog",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operatorworklog",
            name="rate_adjustment_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="operatorworklog",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operatorworklog",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="masterdata.bom",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="bom_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="output_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="reconciliation_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="masterdata.routing",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="routing_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="correction_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="defect_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="qty_remaining",
            field=models.PositiveIntegerField(default=0, verbose_name="Qty Tersisa"),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionstageprogress",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="operatorworklog",
            constraint=models.UniqueConstraint(
                fields=("progress", "operator"), name="uniq_worklog_progress_operator"
            ),
        ),
        migrations.AddField(
            model_name="hppsnapshot",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="hppsnapshot",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hpp_snapshots",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="hppsnapshot",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.material"
            ),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="material_consumptions",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.material"
            ),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_requirements",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="materialrequirement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="materialreservation",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="production.materialrequirement",
            ),
        ),
        migrations.AddField(
            model_name="materialreservation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="productioncost",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costs",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="productioncost",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="reworkorder",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="masterdata.operator"
            ),
        ),
        migrations.AddField(
            model_name="reworkorder",
            name="source_progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rework_orders",
                to="production.productionstageprogress",
            ),
        ),
        migrations.AddField(
            model_name="reworkorder",
            name="target_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.routingstage",
            ),
        ),
        migrations.AddField(
            model_name="reworkorder",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrap_records",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="responsible_operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.operator",
            ),
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="source_progress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="production.productionstageprogress",
            ),
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="wipbalance",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wip_balances",
                to="production.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="wipbalance",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="masterdata.routingstage",
            ),
        ),
        migrations.AddField(
            model_name="wipbalance",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialrequirement",
            constraint=models.UniqueConstraint(
                fields=("production_order", "material"),
                name="uniq_order_material_requirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="wipbalance",
            constraint=models.UniqueConstraint(
                fields=("production_order", "stage"), name="uniq_order_stage_wip"
            ),
        ),
    ]
