# Generated by Django 6.0.6 on 2026-06-26 15:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_material_requirement_snapshots(apps, schema_editor):
    material_requirement = apps.get_model("production", "MaterialRequirement")
    bom_item = apps.get_model("masterdata", "BOMItem")
    db_alias = schema_editor.connection.alias

    requirements = material_requirement.objects.using(db_alias).select_related(
        "production_order",
        "material",
        "material__usage_uom",
        "material__purchase_uom",
    )
    for requirement in requirements.iterator():
        order = requirement.production_order
        material = requirement.material
        snapshot_item = None
        for item in (order.bom_snapshot or {}).get("items", []):
            if str(item.get("material_id")) == str(material.id):
                snapshot_item = item
                break

        bom_line = None
        if snapshot_item is None and order.bom_id:
            bom_line = (
                bom_item.objects.using(db_alias)
                .filter(
                    tenant_id=order.tenant_id,
                    bom_id=order.bom_id,
                    material_id=material.id,
                )
                .first()
            )

        if snapshot_item:
            quantity_per_unit = Decimal(
                str(
                    snapshot_item.get("quantity_per_unit")
                    or snapshot_item.get("quantity")
                    or "0"
                )
            )
            source_bom_item_id = snapshot_item.get("bom_item_id")
            conversion_ratio = Decimal(
                str(snapshot_item.get("conversion_ratio") or material.conversion_ratio)
            )
            shrinkage_percent = Decimal(
                str(
                    snapshot_item.get("shrinkage_percent")
                    or material.shrinkage_percent
                )
            )
            material_code = snapshot_item.get("material_code") or material.code
            material_name = snapshot_item.get("material_name") or material.name
            usage_uom_code = snapshot_item.get("usage_uom_code") or material.usage_uom.code
            purchase_uom_code = (
                snapshot_item.get("purchase_uom_code") or material.purchase_uom.code
            )
        elif bom_line:
            quantity_per_unit = bom_line.quantity
            source_bom_item_id = bom_line.id
            conversion_ratio = material.conversion_ratio
            shrinkage_percent = material.shrinkage_percent
            material_code = material.code
            material_name = material.name
            usage_uom_code = material.usage_uom.code
            purchase_uom_code = material.purchase_uom.code
        else:
            quantity_per_unit = (
                requirement.required_usage_qty / order.target_quantity
                if order.target_quantity
                else Decimal("0")
            )
            source_bom_item_id = None
            conversion_ratio = material.conversion_ratio
            shrinkage_percent = material.shrinkage_percent
            material_code = material.code
            material_name = material.name
            usage_uom_code = material.usage_uom.code
            purchase_uom_code = material.purchase_uom.code

        requirement.source_bom_item_id = source_bom_item_id
        requirement.material_code_snapshot = material_code
        requirement.material_name_snapshot = material_name
        requirement.quantity_per_unit = quantity_per_unit
        requirement.usage_uom_code_snapshot = usage_uom_code
        requirement.purchase_uom_code_snapshot = purchase_uom_code
        requirement.conversion_ratio_snapshot = conversion_ratio
        requirement.shrinkage_percent_snapshot = shrinkage_percent
        requirement.save(
            update_fields=[
                "source_bom_item_id",
                "material_code_snapshot",
                "material_name_snapshot",
                "quantity_per_unit",
                "usage_uom_code_snapshot",
                "purchase_uom_code_snapshot",
                "conversion_ratio_snapshot",
                "shrinkage_percent_snapshot",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_update_default_uom_dimensions'),
        ('production', '0003_hppsnapshot_materialconsumption_materialrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirement',
            name='conversion_ratio_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='material_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='material_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='purchase_uom_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='shrinkage_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='source_bom_item_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='usage_uom_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(
            backfill_material_requirement_snapshots, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.bom'),
        ),
    ]
