# Generated by Django 6.0.6 on 2026-06-20 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Kategori")),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Nama File Asli"),
                ),
                (
                    "stored_path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Path Internal"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(max_length=120, verbose_name="Content Type"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(verbose_name="Ukuran Bytes"),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="SHA-256"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Diarsipkan"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Diarsipkan Pada"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Dibuat"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="core.tenant",
                        verbose_name="Konveksi",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diunggah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Metadata",
                "verbose_name_plural": "File Metadata",
                "db_table": "core_file_metadata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=30, verbose_name="Jenis Dokumen"),
                ),
                (
                    "period",
                    models.CharField(max_length=6, verbose_name="Periode YYYYMM"),
                ),
                (
                    "current_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nomor Saat Ini"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_sequences",
                        to="core.tenant",
                        verbose_name="Konveksi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Sequence",
                "verbose_name_plural": "Document Sequences",
                "db_table": "core_document_sequence",
                "ordering": ["tenant", "document_type", "period"],
                "unique_together": {("tenant", "document_type", "period")},
            },
        ),
    ]
