# Generated by Django 6.0.6 on 2026-06-20 18:19

from django.db import migrations, models


def fill_empty_request_ids(apps, _schema_editor):
    audit_event = apps.get_model("core", "AuditEvent")
    audit_event.objects.filter(request_id__isnull=True).update(request_id="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_filemetadata_documentsequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Request ID"
            ),
        ),
        migrations.RunPython(fill_empty_request_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Request ID"
            ),
        ),
    ]
