# Generated by Django 6.0.6 on 2026-06-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_auditevent_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="resource_id",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="ID Dokumen"
            ),
        ),
        migrations.AddField(
            model_name="filemetadata",
            name="resource_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Tipe Dokumen"
            ),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="deduplication_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=200,
                verbose_name="Kunci Idempotensi",
            ),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbox_events",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Kode Dokumen"
            ),
        ),
        migrations.CreateModel(
            name="BusinessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=7,
                        verbose_name="Margin Default (%)",
                    ),
                ),
                (
                    "significant_scrap_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=100,
                        max_digits=15,
                        verbose_name="Batas Scrap Signifikan",
                    ),
                ),
                (
                    "significant_adjustment_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000000,
                        max_digits=18,
                        verbose_name="Batas Nilai Adjustment Signifikan",
                    ),
                ),
                (
                    "material_alert_escalation_hours",
                    models.PositiveIntegerField(default=24),
                ),
                (
                    "payment_alert_escalation_hours",
                    models.PositiveIntegerField(default=24),
                ),
                ("telegram_chat_ids", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_policy",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_business_policy",
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=80)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("processing", "Diproses"),
                            ("completed", "Selesai"),
                            ("failed", "Gagal"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.filemetadata",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_export_job",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_type", models.CharField(max_length=80)),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_approval_request",
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "action_type"],
                        name="core_approv_tenant__bab335_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("telegram", "Telegram")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("safe_path", models.CharField(blank=True, default="", max_length=500)),
                ("deduplication_key", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("sent", "Terkirim"),
                            ("failed", "Gagal"),
                            ("read", "Dibaca"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_notification",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "channel", "deduplication_key"),
                        name="uniq_notification_delivery",
                    )
                ],
            },
        ),
    ]
